server:
  port: 8081
spring:
  application:
  name: tlq-cn-demo


tlqcn:
  client:
    service-url: tlqcn://10.10.22.175:6650
    service-http-url: http://10.10.22.175:8080
    authentication:
      enabled: false
      token:
    failover-config:
      primary-url: tlqcn://10.10.22.175:6650
      secondary-url: tlqcn://10.10.22.175:6650
      delay: 30
      switch-back-delay: 60
      check-interval: 2000
      check-topic: "persistent://public/default/check_topic"
  function-test-config:
    enabled: false
    topic: "persistent://public/default/topic1"
    public-key-path: gm_-public-key.pem
    private-key-path: gm_-private-key.pem
    enabled-sync-send-test: true
    enabled-async--send-test: true
    enabled-subscribe-type-test: false
    enabled-message-filter-test: false
    enabled-message-seek-test: false
    enabled-broadcast-consume-test: false
    enabled-message-ttl-test: false
    enabled-dead-letter-queue-test: false
    enabled-consumer-retry-test: false
    enabled-delay-message-test: false
    enabled-scheduled-message-test: false
    enabled-message-order-test: false
    enabled-gm-message-test: false
    enabled-gm-tls-test: false
    enabled-message-priority-test: false
    consumer-num: 1
    topic-partition-num: 1
    msg-num: 100
  perf-param-configs:
    enabled: true
    topic: "persistent://public/default/perf_topic"
    enable-perf-sync-test: true
    enable-perf-async-test: true
    batching-max-publish-delay: 10
    batching-max-messages: 1000
    # 每一个测试用例执行的时间
    test-time-per-case: 10_000
    # 性能日志记录时间间隔
    log-interval: 10_000
    # 每一个测试用例之间的间隔
    case-interval: 60_000
    # 测试完毕，关闭生产者和消费者的时间
    close-time: 120_000
    cron: 0 28 19 * * ?
  perf-case-configs:
    - producer-num: 1
      consumer-num: 1
      topic-partition-num: 1
      msg-size: 1024
      per-producer-thread-num: 1
      consume-after-send: false
      sync-ack: false
    - producer-num: 1
      consumer-num: 1
      topic-partition-num: 100
      msg-size: 1024
      per-producer-thread-num: 1
    - producer-num: 1
      consumer-num: 1
      topic-partition-num: 1
      msg-size: 1024
      per-producer-thread-num: 8
    - producer-num: 1
      consumer-num: 1
      topic-partition-num: 100
      msg-size: 1024
      per-producer-thread-num: 8
    - producer-num: 8
      consumer-num: 8
      topic-partition-num: 1
      msg-size: 1024
      per-producer-thread-num: 1
    - producer-num: 8
      consumer-num: 8
      topic-partition-num: 100
      msg-size: 1024
      per-producer-thread-num: 1
    - producer-num: 8
      consumer-num: 8
      topic-partition-num: 1
      msg-size: 1024
      per-producer-thread-num: 8
    - producer-num: 8
      consumer-num: 8
      topic-partition-num: 100
      msg-size: 1024
      per-producer-thread-num: 8

    - producer-num: 1
      consumer-num: 1
      topic-partition-num: 1
      msg-size: 4096
      per-producer-thread-num: 1
    - producer-num: 1
      consumer-num: 1
      topic-partition-num: 100
      msg-size: 4096
      per-producer-thread-num: 1
    - producer-num: 1
      consumer-num: 1
      topic-partition-num: 1
      msg-size: 4096
      per-producer-thread-num: 8
    - producer-num: 1
      consumer-num: 1
      topic-partition-num: 100
      msg-size: 4096
      per-producer-thread-num: 8
    - producer-num: 8
      consumer-num: 8
      topic-partition-num: 1
      msg-size: 4096
      per-producer-thread-num: 1
    - producer-num: 8
      consumer-num: 8
      topic-partition-num: 100
      msg-size: 4096
      per-producer-thread-num: 1
    - producer-num: 8
      consumer-num: 8
      topic-partition-num: 1
      msg-size: 4096
      per-producer-thread-num: 8
    - producer-num: 8
      consumer-num: 8
      topic-partition-num: 100
      msg-size: 4096
      per-producer-thread-num: 8
